### ISSUE TITLE
Doesn't like comma in a string parameter

### ISSUE THREAD

**Issue by spayton** [MrcSnm/define_macro-loader#1]
Never quite found a 'C' like .js preprocessor to provide macro defines, so this is great, but running into a few issues, like this example.

DEFINE(_TEST, (a) =>
{
    console.log(a);
});

_TEST("good good"); // this is good
_TEST("bad, bad");  // doesn't like comma in string

The webpacking error is:

Module parse failed: Unterminated string constant (559:16)
File was processed with these loaders:
\* ./node_modules/@hipreme_entertainment/define_macro-loader/define_macro-loader.js
You may need an additional loader to handle the result of these loaders.
|  // this is good
|
\>     console.log("bad);
|   // doesn't like comma in string
|
i ｢wdm｣: Failed to compile.

**Comment by MrcSnm** [comment]
v.1.2.5 fixes this problem
